### ISSUE TITLE
Can I change the Overlay position with animation?

### ISSUE THREAD

**Issue by costales** [openlayers/ol3#4341]
Hi,

I have an overlay and I would like to move it to another position with a smooth movement. Is this possible? How?

Thanks in advance!

**Comment by fredj** [comment]
You can try to use CSS transition, something like:
```css
.ol-overlay-container {
  transition-property: left, top;
  transition-duration: 0.25s;
  transition-timing-function: linear;
}
```
