### ISSUE TITLE
Cannot select words within first sentence of API docs

### ISSUE THREAD

**Issue by drnextgis** [openlayers/ol3#5093]
Open for example [this](http://openlayers.org/en/v3.14.2/apidoc/ol.source.Raster.html) page and try to select any word in first sentence:

> A source that transforms data from any number of input sources using an array of ...

This problem caused by CSS style from [jaguar.css](https://github.com/openlayers/ol3/blob/master/config/jsdoc/api/template/static/styles/jaguar.css):

``` css
.nameContainer .name, .prettyprint.source .pln {
  padding-top: 50px;
  margin-top: -50px;
}
```

What is the goal of this style?
